"""

Revision ID: 62aa9c65f8f5
Revises: 7216cb3d9248
Create Date: 2023-05-26 06:33:18.936021

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "62aa9c65f8f5"
down_revision = "7216cb3d9248"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case", sa.Column("process", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case", "process")
    # ### end Alembic commands ###
