"""add username as unique

Revision ID: 650f580e0fff
Revises: fbad82eb9200
Create Date: 2023-05-25 02:24:35.958381

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "650f580e0fff"
down_revision = "fbad82eb9200"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_username", table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    # ### end Alembic commands ###
