"""add user_id column

Revision ID: 7216cb3d9248
Revises: f59eb9f6977f
Create Date: 2023-05-26 06:08:23.297546

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7216cb3d9248"
down_revision = "f59eb9f6977f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case", sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case", "user_id")
    # ### end Alembic commands ###
