"""

Revision ID: c9e0f7e5f4e3
Revises: 62aa9c65f8f5
Create Date: 2023-05-26 06:37:13.359157

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9e0f7e5f4e3"
down_revision = "62aa9c65f8f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
